### ISSUE TITLE
Django Compressor error after clean install

### ISSUE THREAD

**Issue by chicagobuss** [arachnys/cabot#166]
Just installed cabot on a fresh AWS 12.04 instance using this guide: http://www.unicoda.com/?p=1624

..and I got these error when I tried to use the webapp:

ERROR 2015-01-02 11:55:26,875 base 20084 140454996674304 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 89, in render_compressed
    cached_offline = self.render_offline(context, forced=forced)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 73, in render_offline
    'You may need to run "python manage.py compress".' % key)
OfflineGenerationError: You have offline compression enabled but key "5f791e890c250326ad4b57e708d81554" is missing from offline manifest. You may need to run "python manage.py compress".
ERROR 2015-01-02 11:55:27,600 base 20082 140454996674304 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/views/defaults.py", line 30, in page_not_found
    body = template.render(RequestContext(request, {'request_path': request.path}))
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 89, in render_compressed
    cached_offline = self.render_offline(context, forced=forced)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 73, in render_offline
    'You may need to run "python manage.py compress".' % key)
OfflineGenerationError: You have offline compression enabled but key "5f791e890c250326ad4b57e708d81554" is missing from offline manifest. You may need to run "python manage.py compress".

I was able to workaround the problem (sort of) by editing /home/ubuntu/cabot/cabot/settings.py and adding "COMPRESS_OFFLINE = False" but I think that's messing other things up, as the CSS doesn't look right in some places now.  Help!

**Comment by dbuxton** [comment]
Thanks for the heads up. This is indeed to do with Django-Compressor but without knowing exactly what you did to set it up, it's hard to debug. 

Is there a deployment step in your config which involves running `./manage.py compress`?

For instance, in the stock `fabfile.py`, this gets run as part of `collect_static` (which is itself part of the deploy process):

https://github.com/arachnys/cabot/blob/474acbe2983dabebc0515fddf8ce9bcd66866e49/fabfile.py#L62

Let me know if that helps. In the meantime I will close because although I agree getting started guide could be better, this isn't actually a bug in the code.
