### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by coagulant** [arachnys/cabot#17]
Haven't checked what's wrong yet.

```
ERROR 2014-01-24 12:57:03,371 base 8628 140590461187840 Internal Server Error: /accounts/password-reset/
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 153, in password_reset
    form.save(**opts)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/contrib/auth/forms.py", line 241, in save
    email = loader.render_to_string(email_template_name, c)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 171, in render_to_string
    return t.render(Context(dictionary))
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 837, in render_node
    return node.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 31, in render
    output = self.nodelist.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 837, in render_node
    return node.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 837, in render_node
    return node.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 426, in render
    raise e
NoReverseMatch: Reverse for 'django.contrib.auth.views.password_reset_confirm' with arguments '()' and keyword arguments '{'uidb36': '3', 'token': '**********'}' not found.
```

**Comment by mattvonrocketstein** [comment]
I'm not sure why "createsuperuser" would fix this, and that doesn't work for me.  Adding an entry to urls.py (per https://docs.djangoproject.com/es/1.9/topics/auth/default/#module-django.contrib.auth.views ) did fix it based on my testing, but note that you will need to make sure email is already setup via SES_HOST, SES_USER, etc
