### ISSUE TITLE
Deployment on 12.04 - Localhost

### ISSUE THREAD

**Issue by JulienChampseix** [arachnys/cabot#184]
Hi Team,

Is it planned to have a procedure step by step for install cabot on local server (not remote) ?

Thanks.
Julien.

**Comment by dbuxton** [comment]
You can fab deploy against localhost if you really want? I don't think this is something we need but if you would like to document or extend the fab script please go ahead.

**Comment by JulienChampseix** [comment]
Is there a way to install without using fabric?

**Comment by dbuxton** [comment]
Fabric is just a nice way of automating various boring installation steps (generating upstart config, provisioning redis, installing dependencies). If you look at the [`deploy`](https://github.com/arachnys/cabot/blob/db554a5192d03ce4df4c88f05b8faeb2da674203/fabfile.py#L106) and `provision` tasks you'll see that most of it is just simple commands...

**Comment by JulienChampseix** [comment]
Following those step for install cabot :

git clone https://github.com/arachnys/cabot.git
cd cabot
cp conf/production.env.example conf/production.env
fab deploy -H root@127.0.0.1

Libs versions:
Python version:  Python 2.7.3
Pip version: pip 6.0.8 from /usr/local/lib/python2.7/dist-packages (python 2.7)
virtualenv version: 12.0.7

i got this error :

```
[root@127.0.0.1] sudo: foreman run python manage.py syncdb -e conf/production.env
[root@127.0.0.1] out: Syncing...
[root@127.0.0.1] out: Traceback (most recent call last):
[root@127.0.0.1] out:   File "manage.py", line 11, in <module>
[root@127.0.0.1] out:     execute_from_command_line(sys.argv)
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
[root@127.0.0.1] out:     utility.execute()
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
[root@127.0.0.1] out:     self.fetch_command(subcommand).run_from_argv(self.argv)
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
[root@127.0.0.1] out:     self.execute(*args, **options.__dict__)
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
[root@127.0.0.1] out:     output = self.handle(*args, **options)
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
[root@127.0.0.1] out:     return self.handle_noargs(**options)
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 92, in handle_noargs
[root@127.0.0.1] out:     syncdb.Command().execute(**options)
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
[root@127.0.0.1] out:     output = self.handle(*args, **options)
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
[root@127.0.0.1] out:     return self.handle_noargs(**options)
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 57, in handle_noargs
[root@127.0.0.1] out:     cursor = connection.cursor()
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 162, in cursor
[root@127.0.0.1] out:     cursor = util.CursorWrapper(self._cursor(), self)
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 132, in _cursor
[root@127.0.0.1] out:     self.ensure_connection()
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
[root@127.0.0.1] out:     self.connect()
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
[root@127.0.0.1] out:     six.reraise(dj_exc_type, dj_exc_value, traceback)
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
[root@127.0.0.1] out:     self.connect()
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 115, in connect
[root@127.0.0.1] out:     self.connection = self.get_new_connection(conn_params)
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 115, in get_new_connection
[root@127.0.0.1] out:     return Database.connect(**conn_params)
[root@127.0.0.1] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
[root@127.0.0.1] out:     conn = _connect(dsn, connection_factory=connection_factory, async=async)
[root@127.0.0.1] out: django.db.utils.OperationalError: could not connect to server: Connection refused
[root@127.0.0.1] out: 	Is the server running on host "localhost" (127.0.0.1) and accepting
[root@127.0.0.1] out: 	TCP/IP connections on port 5432?
[root@127.0.0.1] out:
[root@127.0.0.1] out:
``

Any idea about it ?

**Comment by dbuxton** [comment]
Looks like no postgres running on your instance?
