### ISSUE TITLE
Email Alert: 'User' object has no attribute 'user'

### ISSUE THREAD

**Issue by candland** [arachnys/cabot#190]
All the users have an email setup. I also setup an user profile for each.

Not sure if this matters.

    ERROR 2015-02-24 08:18:18,412 urls 12135 139683153389312 No url file available for plugin cabot_alert_email

This seems to be the main issue.

````
Traceback (most recent call last):
  File "/home/ubuntu/2015-02-23-3c6f4f6/cabot/cabotapp/alert.py", line 50, in send_alert
    alert.send_alert(service, users, duty_officers)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/cabot_alert_email/models.py", line 29, in send_alert
    emails = [u.user.email for u in users]
AttributeError: 'User' object has no attribute 'user'
````

Changing to u.email for u in users fixed this. Where is this code in the project?

**Comment by dbuxton** [comment]
This is actually an issue with https://github.com/bonniejools/cabot-alert-email - can you fix @bonniejools

**Comment by wolfpakz** [comment]
+1
