### ISSUE TITLE
pytz on aws ubuntu 14.04

### ISSUE THREAD

**Issue by tommiatplayfish** [arachnys/cabot#207]
Some funny dependancy problem is filling the celery logs:

Traceback (most recent call last):
  File "/home/ubuntu/venv/bin/celery", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pytz>dev

root@fox2-dev-log2:/home/ubuntu/venv/lib/python2.7/site-packages# ls -la|grep pytz
drwxr-xr-x  3 root root   4096 Mar 30 17:25 pytz
drwxr-xr-x  2 root root   4096 Mar 30 17:25 pytz-2014.10.dist-info

**Comment by dbuxton** [comment]
[This](http://stackoverflow.com/questions/6200056/pip-broke-how-to-fix-distributionnotfound-error) suggests it could be a pip issue - can you see if upgrading fixes for you?

**Comment by markdanko** [comment]
I have also seen this. I am using newest pip:
pip -V
pip 6.0.8 from /usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg (python 2.7)

**Comment by markdanko** [comment]
Also this is the same issue as https://github.com/arachnys/cabot/issues/122.
