### ISSUE TITLE
redis://@localhost:6379/1: invalid password.

### ISSUE THREAD

**Issue by maassql** [arachnys/cabot#209]
* It seemed everything was working.  In the web interface, I created a graphite check, then ran it.  
* Now, when I do, I get the page saying to see the logs.
* The redis address shown in the celery log isn't in the config file I deployed

* from production.env 
```text
# Django settings
CELERY_BROKER_URL=redis://:yourrediskey@localhost:6379/1
DJANGO_SECRET_KEY=our_django_key
```

* web-1.log
```text
ERROR 2015-03-30 22:42:05,842 base 1744 139674310887168 Internal Server Error: /check/run/1/
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)ERROR 2015-03-30 22:42:05,842 base 1744 139674310887168 Internal Server Error: /check/run/1/
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)ERROR 2015-03-30 22:42:05,842 base 1744 139674310887168 Internal Server Error: /check/run/1/
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
...
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/redis/connection.py", line 339, in read_response
    raise response
ResponseError: invalid password
```

* celery-1.log
```text
[2015-03-31 13:22:44,091: ERROR/Beat] beat: Connection error: invalid password. Trying again in 32.0 seconds...
[2015-03-31 13:22:44,322: ERROR/MainProcess] consumer: Cannot connect to redis://@localhost:6379/1: invalid password.
Trying again in 32.00 seconds...
```

* redis is running:
```text
redis      991  0.0  0.1  10676  1188 ?        Ss   Mar30   0:18 /usr/bin/redis-server /etc/redis/redis.conf
```

* ps aux | grep cabot
```text
ubuntu     762  0.0  0.1  48640   624 ?        Ss   Mar30   0:00 su - ubuntu -c cd /home/ubuntu/cabot; export PORT=5000; export CABOT_PLUGINS_ENABLED="cabot_alert_hipchat==1.6.1,cabot_alert_twilio==1.1.4,cabot_alert_email==1.3.1";  export DATABASE_URL="postgres://cabot:cabot@localhost:5432/index";  export DJANGO_SETTINGS_MODULE="cabot.settings";  export HIPCHAT_URL="https://api.hipchat.com/v1/rooms/message";  export LOG_FILE="/home/ubuntu/a_cabot_prod.log";  export PORT="5000";  export VENV="/home/ubuntu/venv";  export TIME_ZONE="Etc/UTC";  export ADMIN_EMAIL="jmaass@cccis.com";  export CABOT_FROM_EMAIL="our_gmail_account@gmail.com";  export CALENDAR_ICAL_URL="our_ics_url";  export CELERY_BROKER_URL="redis://:yourrediskey@localhost:6379/1";  export DJANGO_SECRET_KEY="our_django_secret_key";  export GRAPHITE_API="http://nitro-monitor-2/";  export GRAPHITE_USER="graphite_admin";  export GRAPHITE_PASS="graphite";  export HIPCHAT_ALERT_ROOM="48052";  export HIPCHAT_API_KEY="your_hipchat_api_key";  export JENKINS_API="https://jenkins.example.com/";  export JENKINS_USER="username";  export JENKINS_PASS="password";  export SES_HOST="smtp.gmail.com";  export SES_USER="our_gmail_account@gmail.com";  export SES_PASS="our_email_password";  export SES_PORT="465";  export TWILIO_ACCOUNT_SID="your_account_sid";  export TWILIO_AUTH_TOKEN="your_auth_token";  export TWILIO_OUTGOING_NUMBER="+14155551234";  export WWW_HTTP_HOST="nitro-monitor-4";  export WWW_SCHEME="http";  export TMPDIR=$TMPDIR/cabot/web/1; rm -rf $TMPDIR; mkdir -p $TMPDIR; source $VENV/bin/activate; gunicorn cabot.wsgi:application --config gunicorn.conf >> /var/log/cabot/web-1.log 2>&1
ubuntu     883  0.0  0.1  19532   716 ?        S    Mar30   0:00 -su -c cd /home/ubuntu/cabot; export PORT=5000; export CABOT_PLUGINS_ENABLED="cabot_alert_hipchat==1.6.1,cabot_alert_twilio==1.1.4,cabot_alert_email==1.3.1";  export DATABASE_URL="postgres://cabot:cabot@localhost:5432/index";  export DJANGO_SETTINGS_MODULE="cabot.settings";  export HIPCHAT_URL="https://api.hipchat.com/v1/rooms/message";  export LOG_FILE="/home/ubuntu/a_cabot_prod.log";  export PORT="5000";  export VENV="/home/ubuntu/venv";  export TIME_ZONE="Etc/UTC";  export ADMIN_EMAIL="jmaass@cccis.com";  export CABOT_FROM_EMAIL="our_gmail_account@gmail.com";  export CALENDAR_ICAL_URL="our_ics_url";  export CELERY_BROKER_URL="redis://:yourrediskey@localhost:6379/1";  export DJANGO_SECRET_KEY="our_django_secret_key";  export GRAPHITE_API="http://nitro-monitor-2/";  export GRAPHITE_USER="graphite_admin";  export GRAPHITE_PASS="graphite";  export HIPCHAT_ALERT_ROOM="48052";  export HIPCHAT_API_KEY="your_hipchat_api_key";  export JENKINS_API="https://jenkins.example.com/";  export JENKINS_USER="username";  export JENKINS_PASS="password";  export SES_HOST="smtp.gmail.com";  export SES_USER="our_gmail_account@gmail.com";  export SES_PASS="our_email_password";  export SES_PORT="465";  export TWILIO_ACCOUNT_SID="your_account_sid";  export TWILIO_AUTH_TOKEN="your_auth_token";  export TWILIO_OUTGOING_NUMBER="+14155551234";  export WWW_HTTP_HOST="nitro-monitor-4";  export WWW_SCHEME="http";  export TMPDIR=$TMPDIR/cabot/web/1; rm -rf $TMPDIR; mkdir -p $TMPDIR; source $VENV/bin/activate; gunicorn cabot.wsgi:application --config gunicorn.conf >> /var/log/cabot/web-1.log 2>&1
ubuntu     900  0.0  1.5  46784  9384 ?        S    Mar30   0:09 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/gunicorn cabot.wsgi:application --config gunicorn.conf
ubuntu     914  0.0  2.9  70068 18092 ?        S    Mar30   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/gunicorn cabot.wsgi:application --config gunicorn.conf
ubuntu     917  0.0  2.9  70080 18092 ?        S    Mar30   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/gunicorn cabot.wsgi:application --config gunicorn.conf
ubuntu     920  0.0  2.9  70088 18096 ?        S    Mar30   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/gunicorn cabot.wsgi:application --config gunicorn.conf
ubuntu    4428  0.0  0.2  48640  1524 ?        Ss   12:44   0:00 su - ubuntu -c cd /home/ubuntu/cabot; export PORT=5100; export CABOT_PLUGINS_ENABLED="cabot_alert_hipchat==1.6.1,cabot_alert_twilio==1.1.4,cabot_alert_email==1.3.1";  export DATABASE_URL="postgres://cabot:cabot@localhost:5432/index";  export DJANGO_SETTINGS_MODULE="cabot.settings";  export HIPCHAT_URL="https://api.hipchat.com/v1/rooms/message";  export LOG_FILE="/home/ubuntu/a_cabot_prod.log";  export PORT="5000";  export VENV="/home/ubuntu/venv";  export TIME_ZONE="Etc/UTC";  export ADMIN_EMAIL="jmaass@cccis.com";  export CABOT_FROM_EMAIL="our_gmail_account@gmail.com";  export CALENDAR_ICAL_URL="our_ics_url";  export CELERY_BROKER_URL="redis://:yourrediskey@localhost:6379/1";  export DJANGO_SECRET_KEY="our_django_secret_key";  export GRAPHITE_API="http://nitro-monitor-2/";  export GRAPHITE_USER="graphite_admin";  export GRAPHITE_PASS="graphite";  export HIPCHAT_ALERT_ROOM="48052";  export HIPCHAT_API_KEY="your_hipchat_api_key";  export JENKINS_API="https://jenkins.example.com/";  export JENKINS_USER="username";  export JENKINS_PASS="password";  export SES_HOST="smtp.gmail.com";  export SES_USER="our_gmail_account@gmail.com";  export SES_PASS="our_email_password";  export SES_PORT="465";  export TWILIO_ACCOUNT_SID="your_account_sid";  export TWILIO_AUTH_TOKEN="your_auth_token";  export TWILIO_OUTGOING_NUMBER="+14155551234";  export WWW_HTTP_HOST="nitro-monitor-4";  export WWW_SCHEME="http";  export TMPDIR=$TMPDIR/cabot/celery/1; rm -rf $TMPDIR; mkdir -p $TMPDIR; source $VENV/bin/activate; celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair >> /var/log/cabot/celery-1.log 2>&1
ubuntu    4439  0.0  0.2  19532  1776 ?        S    12:44   0:00 -su -c cd /home/ubuntu/cabot; export PORT=5100; export CABOT_PLUGINS_ENABLED="cabot_alert_hipchat==1.6.1,cabot_alert_twilio==1.1.4,cabot_alert_email==1.3.1";  export DATABASE_URL="postgres://cabot:cabot@localhost:5432/index";  export DJANGO_SETTINGS_MODULE="cabot.settings";  export HIPCHAT_URL="https://api.hipchat.com/v1/rooms/message";  export LOG_FILE="/home/ubuntu/a_cabot_prod.log";  export PORT="5000";  export VENV="/home/ubuntu/venv";  export TIME_ZONE="Etc/UTC";  export ADMIN_EMAIL="jmaass@cccis.com";  export CABOT_FROM_EMAIL="our_gmail_account@gmail.com";  export CALENDAR_ICAL_URL="our_ics_url";  export CELERY_BROKER_URL="redis://:yourrediskey@localhost:6379/1";  export DJANGO_SECRET_KEY="our_django_secret_key";  export GRAPHITE_API="http://nitro-monitor-2/";  export GRAPHITE_USER="graphite_admin";  export GRAPHITE_PASS="graphite";  export HIPCHAT_ALERT_ROOM="48052";  export HIPCHAT_API_KEY="your_hipchat_api_key";  export JENKINS_API="https://jenkins.example.com/";  export JENKINS_USER="username";  export JENKINS_PASS="password";  export SES_HOST="smtp.gmail.com";  export SES_USER="our_gmail_account@gmail.com";  export SES_PASS="our_email_password";  export SES_PORT="465";  export TWILIO_ACCOUNT_SID="your_account_sid";  export TWILIO_AUTH_TOKEN="your_auth_token";  export TWILIO_OUTGOING_NUMBER="+14155551234";  export WWW_HTTP_HOST="nitro-monitor-4";  export WWW_SCHEME="http";  export TMPDIR=$TMPDIR/cabot/celery/1; rm -rf $TMPDIR; mkdir -p $TMPDIR; source $VENV/bin/activate; celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair >> /var/log/cabot/celery-1.log 2>&1
ubuntu    4448  0.0  7.1 170596 43012 ?        S    12:44   0:01 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4456  0.0  6.7 169036 40988 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4458  0.0  6.3 167700 38232 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4459  0.0  6.3 167700 38224 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4460  0.0  6.3 167700 38224 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4461  0.0  6.3 167700 38220 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4462  0.0  6.3 167832 38224 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4463  0.0  6.3 167832 38224 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
postgres  4464  0.0  1.0 127744  6100 ?        Ss   12:44   0:00 postgres: cabot index 127.0.0.1(40371) idle
ubuntu    4465  0.0  6.3 167832 38232 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4466  0.0  6.3 167832 38224 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4467  0.0  6.3 167832 38228 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4468  0.0  6.3 167832 38224 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4469  0.0  6.3 167832 38232 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4470  0.0  6.3 167832 38232 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4471  0.0  6.3 167832 38212 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4472  0.0  6.3 167832 38228 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4473  0.0  6.3 167832 38228 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
ubuntu    4474  0.0  6.3 167832 38228 ?        S    12:44   0:00 /home/ubuntu/venv/bin/python /home/ubuntu/venv/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
```

**Comment by maassql** [comment]
It looks like I fixed the problem on my installation.  Something pushed a configuration into the last line of redis.conf.  I notice that "yourredispassword" is not contained as a configuration in the cabot configuration file.  I'm guessing that at some point, ya'll decided to get rid of the redis password by default?  Since my installation was working at one point, I would guess that what changed redis.conf was code in one of the subsequent deploys I did - whilst adjusting settings.

sudo vim /etc/redis/redis.conf
```text
requirepass yourredispassword
```
to
```text
requirepass yourredispassword
```
then, restart redis to pick up the configuration changes:
sudo service redis-server stop
sudo service redis-server start

**Comment by bufke** [comment]
@maassql I think you meant to say 

`requirepass yourredispassword`

to

`requirepass yourrediskey`

This issue appears still active. Following the current documentation to deploy will result in a server that can't connect to redis and can't do checks.

**Comment by dbuxton** [comment]
@bufke good spot, made sure latest `production.env.example` matches `provision.sh`
