### ISSUE TITLE
"Unhandled error. Please look at logs." On first run.

### ISSUE THREAD

**Issue by dibits** [arachnys/cabot#218]
Looking at the logs I get:

```
2015-04-27 10:09:40 [4110] [INFO] Worker exiting (pid: 4110)
2015-04-27 10:09:40 [4085] [INFO] Handling signal: term
2015-04-27 10:09:40 [4085] [INFO] Shutting down: Master
2015-04-27 10:09:43 [5345] [INFO] Starting gunicorn 18.0
2015-04-27 10:09:43 [5345] [INFO] Listening at: http://127.0.0.1:5000 (5345)
2015-04-27 10:09:43 [5345] [INFO] Using worker: sync
2015-04-27 10:09:43 [5375] [INFO] Booting worker with pid: 5375
2015-04-27 10:09:43 [5376] [INFO] Booting worker with pid: 5376
2015-04-27 10:09:43 [5378] [INFO] Booting worker with pid: 5378
ERROR 2015-04-27 10:09:58,633 base 5375 139835873031936 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 89, in render_compressed
    cached_offline = self.render_offline(context, forced=forced)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 73, in render_offline
    'You may need to run "python manage.py compress".' % key)
OfflineGenerationError: You have offline compression enabled but key "b72934311b7ac34a954aca75c7bdc0dd" is missing from offline manifest. You may need to run "python manage.py compress".
ERROR 2015-04-27 10:10:00,245 base 5376 139835873031936 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/views/defaults.py", line 30, in page_not_found
    body = template.render(RequestContext(request, {'request_path': request.path}))
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 89, in render_compressed
    cached_offline = self.render_offline(context, forced=forced)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 73, in render_offline
    'You may need to run "python manage.py compress".' % key)
OfflineGenerationError: You have offline compression enabled but key "b72934311b7ac34a954aca75c7bdc0dd" is missing from offline manifest. You may need to run "python manage.py compress".
```

Tried running the `python manage.py compress` but nothing changed.

When I run `fab provision` first and the `fab deploy` I get no errors whatsoever.

Any ideas what could be the issue here? Thanks in advance!

**Comment by dibits** [comment]
Finally managed to make this work, not entirely sure why, after adding `export DEBUG=t` to the upstart script in `/etc/init/cabot-web-1.conf`
The variable doesn't seem to change anything as far as I can tell in production mode, but I don't get the error anymore with that change.

**Comment by dbuxton** [comment]
This will mean that it's doing offline compression rather than
pre-compiling the pages. It will still work (hopefully) but could be slow.

**Comment by seekshiva** [comment]
@dibits what do you mean by upstart script? I tried adding `export DEBUG=t` to `/etc/init/cabot-web-1.conf` but the conf file gets regenerated when I do `fab deploy`

**Comment by anandmohan777** [comment]
I am getting the same issue.
In file /var/log/cabot/web-1.log see the errors:
==========================   
   bit = self.render_node(node, context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 89, in render_compressed
    cached_offline = self.render_offline(context, forced=forced)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 73, in render_offline
    'You may need to run "python manage.py compress".' % key)
OfflineGenerationError: You have offline compression enabled but key "b72934311b7ac34a954aca75c7bdc0dd" is missing from offline manifest. You may need to run "python manage.py compress".

So as being suggested above I changed the file "/cabot/upstart/process.conf.erb"
and added "export DEBUG=t" at the top and run the fab deploy again. 
Still getting the same error!

@dibits @dbuxton @seekshiva : Please suggest me what should I do now?
