### ISSUE TITLE
Permission Denied during Deploy

### ISSUE THREAD

**Issue by wstiern** [arachnys/cabot#243]
Hi. I'm getting the following error when trying to provision. Confirmed that the cabot user and postgres user both have password-less sudo rights. Any help provided would be appreciated as I've rummaged around through the fabfiles and can't really figure out what the problem is. Thanks in advance!

````
[root@cabot.server] sudo: mkdir -p /var/log/cabot/
[root@cabot.server] sudo: chmod -R 777 /var/log/cabot/
[root@cabot.server] sudo: test -d /home/cabot/venv
[root@cabot.server] sudo: psql -c "CREATE USER cabot WITH NOCREATEDB NOCREATEUSER ENCRYPTED PASSWORD E'cabot'"
[root@cabot.server] out: /bin/bash: line 0: cd: /home/cabot/2015-08-06-f5f201c: Permission denied
[root@cabot.server] out: 


Warning: sudo() received nonzero return code 1 while executing 'psql -c "CREATE USER cabot WITH NOCREATEDB NOCREATEUSER ENCRYPTED PASSWORD E'cabot'"'!

[root@cabot.server] sudo: psql -c "CREATE DATABASE index WITH OWNER cabot"
[root@cabot.server] out: /bin/bash: line 0: cd: /home/cabot/2015-08-06-f5f201c: Permission denied
[root@cabot.server] out: 


Warning: sudo() received nonzero return code 1 while executing 'psql -c "CREATE DATABASE index WITH OWNER cabot"'!

[root@cabot.server] sudo: foreman run -e conf/production.env /home/cabot/venv/bin/pip install --editable /home/cabot/2015-08-06-f5f201c --exists-action=w
[root@cabot.server] out: /usr/local/share/gems/gems/foreman-0.78.0/lib/foreman/cli.rb:92: warning: Insecure world writable dir /mnt/Production/Apps/HAProxy/ in PATH, mode 040777
[root@cabot.server] out: Obtaining file:///home/cabot/2015-08-06-f5f201c
[root@cabot.server] out:   Running setup.py egg_info for package from file:///home/cabot/2015-08-06-f5f201c
[root@cabot.server] out:     Traceback (most recent call last):
[root@cabot.server] out:       File "<string>", line 3, in <module>
[root@cabot.server] out:     ImportError: No module named setuptools.command
[root@cabot.server] out:     Complete output from command python setup.py egg_info:
[root@cabot.server] out:     Traceback (most recent call last):
[root@cabot.server] out: 
[root@cabot.server] out:   File "<string>", line 3, in <module>
[root@cabot.server] out: 
[root@cabot.server] out: ImportError: No module named setuptools.command
[root@cabot.server] out: 
[root@cabot.server] out: ----------------------------------------
[root@cabot.server] out: Cleaning up...
[root@cabot.server] out: Command python setup.py egg_info failed with error code 1 in /home/cabot/2015-08-06-f5f201c
[root@cabot.server] out: Storing complete log in /root/.pip/pip.log
[root@cabot.server] out: 


Fatal error: sudo() received nonzero return code 1 while executing!

Requested: foreman run -e conf/production.env /home/cabot/venv/bin/pip install --editable /home/cabot/2015-08-06-f5f201c --exists-action=w
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "cd /home/cabot/2015-08-06-f5f201c && foreman run -e conf/production.env /home/cabot/venv/bin/pip install --editable /home/cabot/2015-08-06-f5f201c --exists-action=w"

Aborting.
````

**Comment by dbuxton** [comment]
What's the output of running `sudo psql -c "CREATE USER cabot WITH NOCREATEDB NOCREATEUSER ENCRYPTED PASSWORD E'cabot'"`?

**Comment by wstiern** [comment]
````
cabot@lga-cabot01 ~ $ sudo psql -c "CREATE USER cabot WITH NOCREATEDB NOCREATEUSER ENCRYPTED PASSWORD E'cabot'"
psql: FATAL:  role "root" does not exist
````

Worth mentioning that I have zero skills with Postgres. :)

**Comment by wstiern** [comment]
Ok, managed to get the root user and database created, now getting this:
````
cabot@lga-cabot01 ~ $ sudo psql -c "CREATE USER cabot WITH NOCREATEDB NOCREATEUSER ENCRYPTED PASSWORD E'cabot'"
ERROR:  permission denied to create role
````

**Comment by wstiern** [comment]
Ok, managed to get superuser permissions to the root and postgres users, now back to the original error, which seems to be mostly related to permission denied when changing directories to /home/cabot/2015-08-06-f5f201c.

**Comment by wstiern** [comment]
Ok, commented out the bits from the fabfile that rsync the dirs and chown'd everything in that dir to 777 which seems to have nixed the perms issue, but now it still throws the "No module named setuptools.command" error.

**Comment by wstiern** [comment]
Now I'm getting all the way to the end of the line, before this happens:
````
Installing collected packages: distribute, dj-database-url, django-appconf, django-celery, django-celery-with-redis, django-compressor, django-filter, django-jsonify, django-mptt, django-polymorphic, django-redis, django-smtp-ssl, djangorestframework, gunicorn, gevent, hiredis, httplib2, icalendar, kombu, mock, psycogreen, psycopg2, pytz, redis, requests, six, twilio, python-dateutil, django-auth-ldap, cabot-alert-hipchat, cabot-alert-twilio, cabot-alert-email, cabot, greenlet, python-ldap
  Running setup.py install for distribute
    Before install bootstrap.
    Scanning installed packages
    Setuptools installation detected at /home/cabot/venv/lib/python2.7/site-packages
    Non-egg installation
    Removing elements out of the way...
    Renaming /home/cabot/venv/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg-info into /home/cabot/venv/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg-info.OLD.1438894130.94
    Renaming /home/cabot/venv/lib/python2.7/site-packages/setuptools into /home/cabot/venv/lib/python2.7/site-packages/setuptools.OLD.1438894130.94
    Could not find the /home/cabot/venv/lib/python2.7/site-packages/pkg_resources.py element of the Setuptools distribution
    Could not find the /home/cabot/venv/lib/python2.7/site-packages/site.py element of the Setuptools distribution
    Patched done.
    Relaunching...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    NameError: name 'install' is not defined
    Complete output from command /home/cabot/venv/bin/python -c "import setuptools;__file__='/home/cabot/venv/build/distribute/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-UoysuU-record/install-record.txt --single-version-externally-managed --install-headers /home/cabot/venv/include/site/python2.7:
    Before install bootstrap.

Scanning installed packages

Setuptools installation detected at /home/cabot/venv/lib/python2.7/site-packages

Non-egg installation

Removing elements out of the way...

Renaming /home/cabot/venv/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg-info into /home/cabot/venv/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg-info.OLD.1438894130.94

Renaming /home/cabot/venv/lib/python2.7/site-packages/setuptools into /home/cabot/venv/lib/python2.7/site-packages/setuptools.OLD.1438894130.94

Could not find the /home/cabot/venv/lib/python2.7/site-packages/pkg_resources.py element of the Setuptools distribution

Could not find the /home/cabot/venv/lib/python2.7/site-packages/site.py element of the Setuptools distribution

Patched done.

Relaunching...

Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'install' is not defined
````

Google hivemind seems to think this is related to the Distribute package being deprecated in favor of SetupTools.

**Comment by wstiern** [comment]
Ended up blasting the venv entirely and recreating it. Managed to get all the way through the installation, but now I'm getting this in the Celery worker log:
````
[2015-08-06 17:52:54,696: ERROR/Beat] beat: Connection error: Client sent AUTH, but no password is set. Trying again in 32.0 seconds...
[2015-08-06 17:53:26,663: ERROR/MainProcess] consumer: Cannot connect to redis://@localhost:6379/1: Client sent AUTH, but no password is set.
Trying again in 32.00 seconds...
````

**Comment by wstiern** [comment]
Incorrectly configured Redis environment. All daemons seem to be starting now, though the connection is still refused when I try to hit :5000 on the box. Done for today though and the original issue is resolved, so closing.
