### ISSUE TITLE
how to activate custom alert plugin?

### ISSUE THREAD

**Issue by blysik** [arachnys/cabot#272]
I'm working on a private (for now) plugin.  I've slightly hacked setup.py to install it from a git repository:

```
dependency_links=[
        'git+https:/xxx.com/blysik/cabot-alert-alerta.git/#egg=cabot-alert-alerta-1.0.3'
    ],
```

At the top of setup.py I have:
```
os.system('pip install git+https://xxx.com/blysik/cabot-alert-alerta.git@master')
```

And of course, I have:
```
export CABOT_PLUGINS_ENABLED="cabot_alert_hipchat==1.6.1,cabot_alert_twilio==1.1.4,cabot_alert_email==1.3.1,cabot_alert_alerta==1.0.3"
```

However, I can't get this new plugin to get listed.  In the Django admin console I see a 'blank' plugin line with no name.  However, I've properly set a name value in my plugin.

I've run syncdb and migrations, and it looks good:
```
root@09b32d6e9f07:~# python manage.py syncdb
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.messages
 > django.contrib.staticfiles
 > django.contrib.admin
 > south
 > compressor
 > polymorphic
 > mptt
 > jsonify
 > rest_framework
 > cabot_alert_hipchat
 > cabot_alert_twilio
 > cabot_alert_email
 > cabot_alert_alerta

Not synced (use migrations):
 - djcelery
 - cabot.cabotapp
(use ./manage.py migrate to migrate these)
root@09b32d6e9f07:~# python manage.py migrate cabotapp --noinput
Running migrations for cabotapp:
- Nothing to migrate.
 - Loading initial data for cabotapp.
Installed 0 object(s) from 0 fixture(s)
```

Any clues?

**Comment by dbuxton** [comment]
First, I think you should be able to pass through the git source of the plugin via the command line rather than hacking around `dependency_links`

Without access to the source it's hard to say what's happening here, I'm afraid. @bonniejools any ideas?

**Comment by blysik** [comment]
Here's my models.py for now.  Note that I'm horrible with python:
```
from django.db import models
from cabot.cabotapp.alert import AlertPlugin

from os import environ as env

from django.conf import settings
from django.core.urlresolvers import reverse
from django.template import Context, Template

import requests

#text_template = "Service {{ service.name }} {{ scheme }}://{{ host }}{% url 'service' pk=service.id %}"
text_template = "Test text"

class AlertaAlert(AlertPlugin):
    name = "Alerta"
    author = "Bruce Lysik"

    def send_alert(self, service, users, duty_officers):

        if service.overall_status == service.WARNING_STATUS:
            severity = 'warning'
        if service.overall_status == service.ERROR_STATUS:
            severity = 'critical'
        if service.overall_status == service.PASSING_STATUS:
            severity = 'normal'

        c = Context({
            'service': service,
            'host': settings.WWW_HTTP_HOST,
            'scheme': settings.WWW_SCHEME,
        })
        text = Template(text_template).render(c)

        for check in service.all_failing_checks:
            self._send_alerta_alert(resource=check.name, event=check.category, service=service.name, severity=severity, text=text, origin='cabot')

        for check in service.all_passing_checks:
            self._send_alerta_alert(resource=check.name, event=check.category, service=service.name, severity='normal', text=text, origin='cabot')

    def _send_alerta_alert(self, resource, event, service, severity='normal', text='', origin='cabot'):
        alerta_endpoint = env.get('ALERTA_ENDPOINT')
        headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}
        payload = {'resource': resource, 'event': event, 'service': service, 'severity': severity, 'text': text, 'origin': origin, 'environment': 'Production'}
        resp = requests.post(alerta_endpoint + '/alert', json=payload, headers=headers)
```

**Comment by blysik** [comment]
Okay, one thing I changed just now that seemed to help: 
* I run the syncdb and migrate as part of my Procfile

I'm running this in a heroku-type environment, and thought I did that stuff correctly from a shell.  But it appears not.

**Comment by blysik** [comment]
Related question:

Is there any way to have 'global' alerts?  ie, I want /every/ alert to go through a specific plugin, without needing to configure everything individually.

**Comment by blysik** [comment]
And now to finally debug my errors:
```
[2015-10-15 09:46:13,469: ERROR/Worker-3] Could not sent Alerta alert
Traceback (most recent call last):
  File "/app/cabot/cabotapp/alert.py", line 50, in send_alert
    alert.send_alert(service, users, duty_officers)
  File "/app/.heroku/python/lib/python2.7/site-packages/cabot_alert_alerta/models.py", line 35, in send_alert
    for check in service.all_failing_checks:
TypeError: 'instancemethod' object is not iterable
```

**Comment by dbuxton** [comment]
sounds like you need `service.all_failing_checks()` for that last one.

At the moment we don't have a way of forcing a single plugin globally, but it would be easy enough to script with the API

**Comment by blysik** [comment]
I've resolved that one, I believe.  Now I'm wondering, how do I get at the actual check that failed, from an alert?  I want to do something like:
```
        self._send_alerta_alert(resource=check.name, event=check.category, service=service.name, severity=severity, text=text, origin='cabot')
```

But "check" doesn't appear to exist.  (I think I may have made it up while prototyping the plugin out.):
```
Traceback (most recent call last):
  File "/app/cabot/cabotapp/alert.py", line 50, in send_alert
    alert.send_alert(service, users, duty_officers)
  File "/app/.heroku/python/lib/python2.7/site-packages/cabot_alert_alerta/models.py", line 42, in send_alert
    self._send_alerta_alert(resource=check.name, event=check.category, service=service.name, severity=severity, text=text, origin='cabot')
NameError: global name 'check' is not defined
```

Is there a way to do this?

**Comment by blysik** [comment]
For reference, this is working for me, minus the question I asked previously:

```
from django.db import models
from cabot.cabotapp.alert import AlertPlugin

from os import environ as env

from django.conf import settings
from django.core.urlresolvers import reverse
from django.template import Context, Template

import requests

text_template = "{{ scheme }}://{{ host }}{% url 'service' pk=service.id %}: Service {{ service.name }} {% if service.overall_status == service.PASSING_STATUS %}is back to normal{% else %}reporting {{ service.overall_status }} status{% endif %}."

class AlertaAlert(AlertPlugin):
    name = "Alerta"
    author = "Bruce Lysik"

    def send_alert(self, service, users, duty_officers):

        if service.overall_status == service.WARNING_STATUS:
            severity = 'warning'
        elif service.overall_status == service.ERROR_STATUS:
            severity = 'major'
        elif service.overall_status == service.CRITICAL_STATUS:
            severity = 'critical'
        elif service.overall_status == service.PASSING_STATUS:
            severity = 'normal'

        c = Context({
            'service': service,
            'host': settings.WWW_HTTP_HOST,
            'scheme': settings.WWW_SCHEME
        })
        text = Template(text_template).render(c)


        print "ALERTA DEBUG: resouce: " + service.name + ", event: CarbotErr, service: " + service.name + ", severity: " + severity + ", text: " + text + ", origin: cabot"
        self._send_alerta_alert(resource=service.name, event='CabotErr', service=service.name, severity=severity, text=text, origin='cabot')

    def _send_alerta_alert(self, resource, event, service, severity, text, origin='cabot'):
        alerta_endpoint = env.get('ALERTA_ENDPOINT')
        headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}
        payload = {'resource': resource, 'event': event, 'service': [service], 'severity': severity, 'text': text, 'origin': origin, 'environment': 'Production'}
        resp = requests.post(alerta_endpoint + '/alert', json=payload, headers=headers)
        print "ALERTA DEBUG: resp.text: " + resp.text
```

**Comment by dbuxton** [comment]
So can I close this? What is the remaining issue?

**Comment by blysik** [comment]
Sorry, this can be closed.  I'll open more specific issues for other questions.  Thanks!
