### ISSUE TITLE
Celery blocked after redis hit 'maxmemory'

### ISSUE THREAD

**Issue by iliyanotlioneberia** [arachnys/cabot#311]
In my case I have got 'maxmemory' set on redis with volatile-ttl policy, which will remove the key with the nearest expire time. The problem here is that 'celery' key/list which stores all tasks id etc (not used by cabot) does not have expiry timer set and when maxmemory is hit, no more tasks are run. Is anyone experiencing/fixing this?

**Comment by dbuxton** [comment]
Sounds like a more generic celery issue. I've never seen this but would be interested to see if others have.

**Comment by iliyanotlioneberia** [comment]
Thank you for your reply. For example when I am in redis-cli and do 'info keyspace' this is the output 
```
# Keyspace
db1:keys=6,expires=0,avg_ttl=0
```
and 'ttl celery'
```
(integer) -1
```

Based on redis documentation:
```
Expire 

- 1 if the timeout was set.
- 0 if key does not exist or the timeout could not be set.

TTL

- The command returns -2 if the key does not exist.
- The command returns -1 if the key exists but has no associated expire.
```

**Comment by mattvonrocketstein** [comment]
Are you deploying with default stuff in https://github.com/arachnys/cabot/blob/master/fabfile.py or is your redis/celery customized and pre-existing?  I'm facing a intermittent memory issue as well but I've only just started to debug.  I experience instability about once a week, and restarting services always fixes it.  I've got ~50 checks running on a otherwise lightly-used t2.micro in AWS.

**Comment by mindriot88** [comment]
In our case we see a build up of items within the celery key in redis, it caused us a couple of OOM issues for a time running > 1000 checks.

We set maxmemory within our redis.conf to mitigate this, I the issue I think the OP is describing occurs when you hit your max memory allocation new tasks are no longer created for celery to process.
# maxmemory <bytes>
maxmemory 1877791997

This is an example of the error from our celery logs, clearing the celery key manually within redis will clear this issue.
```
Traceback (most recent call last):
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/celery-3.1.7-py2.7.egg/celery/app/trace.py", line 238, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/celery-3.1.7-py2.7.egg/celery/app/trace.py", line 416, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/venv/cabot/cabot/cabotapp/tasks.py", line 36, in run_status_check
    check.run()
  File "/opt/venv/cabot/cabot/cabotapp/models.py", line 519, in run
    self.save()
  File "/opt/venv/cabot/cabot/cabotapp/models.py", line 545, in save
    self.update_related_instances()
  File "/opt/venv/cabot/cabot/cabotapp/models.py", line 566, in update_related_instances
    update_instance.delay(instance.id)
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/celery-3.1.7-py2.7.egg/celery/app/task.py", line 452, in delay
    return self.apply_async(args, kwargs)
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/celery-3.1.7-py2.7.egg/celery/app/task.py", line 554, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/celery-3.1.7-py2.7.egg/celery/app/base.py", line 321, in send_task
    reply_to=reply_to or self.oid, **options
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/celery-3.1.7-py2.7.egg/celery/app/amqp.py", line 299, in publish_task
    **kwargs
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/kombu-3.0.8-py2.7.egg/kombu/messaging.py", line 166, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/kombu-3.0.8-py2.7.egg/kombu/connection.py", line 440, in _ensured
    return fun(*args, **kwargs)
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/kombu-3.0.8-py2.7.egg/kombu/messaging.py", line 182, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/kombu-3.0.8-py2.7.egg/kombu/transport/virtual/__init__.py", line 523, in basic_publish
    message, exchange, routing_key, **kwargs
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/kombu-3.0.8-py2.7.egg/kombu/transport/virtual/exchange.py", line 61, in deliver
    _put(queue, message, **kwargs)
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/kombu-3.0.8-py2.7.egg/kombu/transport/redis.py", line 568, in _put
    client.lpush(self._q_for_pri(queue, pri), dumps(message))
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/redis-2.9.0-py2.7.egg/redis/client.py", line 1052, in lpush
    return self.execute_command('LPUSH', name, *values)
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/redis-2.9.0-py2.7.egg/redis/client.py", line 461, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/redis-2.9.0-py2.7.egg/redis/client.py", line 471, in parse_response
    response = connection.read_response()
  File "/opt/venv/cabot_venv/local/lib/python2.7/site-packages/redis-2.9.0-py2.7.egg/redis/connection.py", line 339, in read_response
    raise response
ResponseError: OOM command not allowed when used memory > 'maxmemory'.
```

**Comment by iliyanotlioneberia** [comment]
I am cooking a fix for this, I will let it doing its thing and see if it works as expected. If it does I maybe can do a pull. I think the only scenario people are going to see this bug is if they are running checks on a lot of instances

**Comment by iliyanotlioneberia** [comment]
This issue happens to be related with the number of tasks running per some time interval and the way we are running workers when and if we don't allocate enough machine power.

**Comment by niksite** [comment]
Hi, I've just got the same issue, could you please elaborate a bit regarding fix you have applied?

**Comment by iliyanotlioneberia** [comment]
From what I remember I think we migrated to multi core cpu with multithreaded celery setup. This fixed it for us @niksite
