### ISSUE TITLE
ERROR when using duta rota

### ISSUE THREAD

**Issue by teejaybugge** [arachnys/cabot#364]
When setting CALENDAR_ICAL_URL to the private address of the calendar as described in http://cabotapp.com/use/rota.html the following error occurs:

> [2016-07-19 11:33:17,737: ERROR/MainProcess] Task cabot.cabotapp.tasks.update_shifts[d83c1562-aafb-48f6-b821-8177b248b9c0] raised unexpected: KeyError('dtend',)
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/2016-07-19-718120c/cabot/cabotapp/tasks.py", line 79, in update_shifts
    _update_shifts()
  File "/home/ubuntu/2016-07-19-718120c/cabot/cabotapp/models.py", line 945, in update_shifts
    events = get_events()
  File "/home/ubuntu/2016-07-19-718120c/cabot/cabotapp/calendar.py", line 19, in get_events
    'end': component.decoded('dtend'),
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/icalendar/cal.py", line 313, in decoded
    raise KeyError, name
KeyError: 'dtend'

Is there a fix for this?

**Comment by dbuxton** [comment]
Can you share the raw iCal file?

**Comment by teejaybugge** [comment]
Looks like this;

> BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Cabottest
X-WR-TIMEZONE:Europe/Copenhagen
X-WR-CALDESC:
BEGIN:VEVENT
DTSTART:20160719T130000Z
DTEND:20160719T160000Z
DTSTAMP:20160719T102406Z
UID:kf6gd4uc1hue70m7gkb7fdtsrc@google.com
CREATED:20160719T091318Z
DESCRIPTION:
LAST-MODIFIED:20160719T091320Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:troels
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR

**Comment by dbuxton** [comment]
It appears from #365 that Cabot parses your ical file fine.

I suspect the issue may be that you're not actually getting an ical file back from Google (i.e. they are blocking you or you're not authorized properly).

Closing this as invalid.
