### ISSUE TITLE
Ubuntu 12.04 fatal error during deploy 

### ISSUE THREAD

**Issue by hajzso** [arachnys/cabot#378]
Fresh Digitalocean instance. This issue might be related: https://github.com/arachnys/cabot/issues/326  --  I tried the solution but it didn't work for me. 

I'm getting the following error:

```
[ubuntu@45.55.88.209] sudo: foreman run -e conf/production.env python manage.py syncdb --noinput
[ubuntu@45.55.88.209] out: Traceback (most recent call last):
[ubuntu@45.55.88.209] out:   File "manage.py", line 11, in <module>
[ubuntu@45.55.88.209] out:     execute_from_command_line(sys.argv)
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
[ubuntu@45.55.88.209] out:     utility.execute()
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
[ubuntu@45.55.88.209] out:     self.fetch_command(subcommand).run_from_argv(self.argv)
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
[ubuntu@45.55.88.209] out:     commands = get_commands()
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 107, in get_commands
[ubuntu@45.55.88.209] out:     apps = settings.INSTALLED_APPS
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
[ubuntu@45.55.88.209] out:     self._setup(name)
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
[ubuntu@45.55.88.209] out:     self._wrapped = Settings(settings_module)
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
[ubuntu@45.55.88.209] out:     mod = importlib.import_module(self.SETTINGS_MODULE)
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
[ubuntu@45.55.88.209] out:     __import__(name)
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/2016-09-25-ebb3d22/cabot/__init__.py", line 5, in <module>
[ubuntu@45.55.88.209] out:     from .celery import app as celery_app
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/2016-09-25-ebb3d22/cabot/celery.py", line 5, in <module>
[ubuntu@45.55.88.209] out:     from celery import Celery
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/celery/five.py", line 306, in __getattr__
[ubuntu@45.55.88.209] out:     module = __import__(self._object_origins[name], None, None, [name])
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/celery/app/__init__.py", line 14, in <module>
[ubuntu@45.55.88.209] out:     from celery import _state
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/celery/_state.py", line 20, in <module>
[ubuntu@45.55.88.209] out:     from celery.utils.threads import LocalStack
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/celery/utils/__init__.py", line 25, in <module>
[ubuntu@45.55.88.209] out:     from kombu.entity import Exchange, Queue
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/kombu/entity.py", line 10, in <module>
[ubuntu@45.55.88.209] out:     from .abstract import MaybeChannelBound, Object
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/kombu/abstract.py", line 12, in <module>
[ubuntu@45.55.88.209] out:     from .connection import maybe_channel
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/kombu/connection.py", line 19, in <module>
[ubuntu@45.55.88.209] out:     from kombu import exceptions
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/kombu/exceptions.py", line 12, in <module>
[ubuntu@45.55.88.209] out:     from amqp import ChannelError, ConnectionError, ResourceError
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/amqp/__init__.py", line 48, in <module>
[ubuntu@45.55.88.209] out:     from .basic_message import Message      # noqa
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/amqp/basic_message.py", line 29, in <module>
[ubuntu@45.55.88.209] out:     from .serialization import GenericContent
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/amqp/serialization.py", line 33, in <module>
[ubuntu@45.55.88.209] out:     from .exceptions import FrameSyntaxError
[ubuntu@45.55.88.209] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/amqp/exceptions.py", line 264, in <module>
[ubuntu@45.55.88.209] out:     _method_name
[ubuntu@45.55.88.209] out: TypeError: Struct() argument 1 must be string, not unicode
[ubuntu@45.55.88.209] out:

Requested: foreman run -e conf/production.env python manage.py syncdb --noinput
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "cd /home/ubuntu/2016-09-25-ebb3d22 >/dev/null && source /home/ubuntu/venv/bin/activate && foreman run -e conf/production.env python manage.py syncdb --noinput"

Aborting.

```

**Comment by dbuxton** [comment]
@hajzso there have been some breaking dependency changes - we are working on getting it in a good state using docker-compose but Cabot's not easily deployable from scratch right now.

@JeanFred can we get master into a good state soon?

**Comment by jeromer** [comment]
ref https://github.com/celery/py-amqp/pull/96

**Comment by jeromer** [comment]
This seems to fix the problem. Hopefully this does not create other problems ...

```
diff --git a/requirements.txt b/requirements.txt
index 1bb5de9..dd89b69 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -2,7 +2,7 @@ Django==1.6.11
 Markdown==2.5
 PyJWT==0.1.2
 South==1.0
-amqp>=1.4.9
+amqp<2.0
 anyjson==0.3.3
 argparse==1.2.1
 celery[redis]==3.1.23
```

**Comment by xinity** [comment]
just had the issue on a debian wheezy custom deployment :(
fixed by removing amqp2.1.0 and installing amqp1.4.9

maybe we should definitely freeze library versions to avoid those kind of issues ?

**Comment by dbuxton** [comment]
Yes sounds like a good idea, can you send a PR?
