### ISSUE TITLE
Unhandled error when adding runbook link

### ISSUE THREAD

**Issue by mikeder** [arachnys/cabot#387]
I get the below errors in the UI and logs when trying to add a link to a runbook:

```
 Unhandled error. Please look at logs. 
```

```
09:26:29 web.1    | ERROR 2016-10-13 13:26:29,004 base 3157 140542469994240 Internal Server Error: /service/update/2/
09:26:29 web.1    | Traceback (most recent call last):
09:26:29 web.1    |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
09:26:29 web.1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
09:26:29 web.1    |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
09:26:29 web.1    |     return self.dispatch(request, *args, **kwargs)
09:26:29 web.1    |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
09:26:29 web.1    |     return bound_func(*args, **kwargs)
09:26:29 web.1    |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
09:26:29 web.1    |     return view_func(request, *args, **kwargs)
09:26:29 web.1    |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
09:26:29 web.1    |     return func(self, *args2, **kwargs2)
09:26:29 web.1    |   File "/home/ubuntu/2016-10-12-689449f/cabot/cabotapp/views.py", line 34, in dispatch
09:26:29 web.1    |     return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)
09:26:29 web.1    |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
09:26:29 web.1    |     return handler(request, *args, **kwargs)
09:26:29 web.1    |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 228, in post
09:26:29 web.1    |     return super(BaseUpdateView, self).post(request, *args, **kwargs)
09:26:29 web.1    |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 170, in post
09:26:29 web.1    |     if form.is_valid():
09:26:29 web.1    |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/forms/forms.py", line 129, in is_valid
09:26:29 web.1    |     return self.is_bound and not bool(self.errors)
09:26:29 web.1    |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/forms/forms.py", line 121, in errors
09:26:29 web.1    |     self.full_clean()
09:26:29 web.1    |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/forms/forms.py", line 273, in full_clean
09:26:29 web.1    |     self._clean_fields()
09:26:29 web.1    |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/forms/forms.py", line 291, in _clean_fields
09:26:29 web.1    |     value = getattr(self, 'clean_%s' % name)()
09:26:29 web.1    |   File "/home/ubuntu/2016-10-12-689449f/cabot/cabotapp/views.py", line 351, in clean_runbook_link
09:26:29 web.1    |     URLValidator()(value)
09:26:29 web.1    | NameError: global name 'URLValidator' is not defined
09:26:30 web.1    | [13/Oct/2016 13:26:30] "POST /service/update/2/ HTTP/1.0" 500 106
```

**Comment by JeanFred** [comment]
So this was definitely working in the branch, so it must have been me messing up that import when rebasing #331…

**Comment by mikeder** [comment]
:+1: thanks for the speedy fix
