### ISSUE TITLE
Getting 500 at / and tons of django error emails

### ISSUE THREAD

**Issue by VAdamec** [arachnys/cabot#584]
Hi,
 cabot seems to work without any problem, but some internal checks failing. It tries to get / but get 302 (redirect to https), then 302 to /services and then get 500. Maybe issue with SSL certificate ? Or docker issue with accessing same server on which it running ? Any help would  be appreciated.

- Django mail report
```
"GET / HTTP/1.1" 500 59

Report
"GET / HTTP/1.1" 500 59

Django Version: 1.10.6
Python Executable: /usr/bin/python
Python Version: 2.7.12
Python Path: ['/code', '/usr/lib/python27.zip', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/lib/python2.7/site-packages', '/code']
Server time: Wed, 29 Nov 2017 09:12:25 +0000
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'compressor',
 'polymorphic',
 'jsonify',
 'cabot.cabotapp',
 'rest_framework',
 'cabot_alert_hipchat',
 'cabot_alert_slack',
 'cabot_alert_email')
Installed Middleware:
('whitenoise.middleware.WhiteNoiseMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')

Request data not supplied
```

- Docker log
```
web_1     | INFO 2017-11-29 09:13:39,863 basehttp 24 140313549085360 "GET / HTTP/1.1" 302 0
web_1     | INFO 2017-11-29 09:13:39,863 basehttp 24 140313549085360 "GET / HTTP/1.1" 302 0
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
web_1     |     self.finish_response()
web_1     |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
web_1     |     self.write(data)
web_1     |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
web_1     |     self.send_headers()
web_1     |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
web_1     |     self.send_preamble()
web_1     |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 194, in send_preamble
web_1     |     'Date: %s\r\n' % format_date_time(time.time())
web_1     |   File "/usr/lib/python2.7/socket.py", line 328, in write
web_1     |     self.flush()
web_1     |   File "/usr/lib/python2.7/socket.py", line 307, in flush
web_1     |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
web_1     | error: [Errno 104] Connection reset by peer
web_1     | ERROR 2017-11-29 09:13:39,864 basehttp 24 140313549085360 "GET / HTTP/1.1" 500 59
web_1     | ERROR 2017-11-29 09:13:39,864 basehttp 24 140313549085360 "GET / HTTP/1.1" 500 59
web_1     | INFO 2017-11-29 09:13:39,955 basehttp 24 140313549085360 - Broken pipe from ('xxx.xxx.xxx.xxx, 49286)
web_1     |
web_1     | INFO 2017-11-29 09:13:39,955 basehttp 24 140313549085360 - Broken pipe from ('xxx.xxx.xxx.xxx', 49286)
web_1     |
```

**Comment by adriankirchner** [comment]
Is there a way to disable the tons of error mails instead?

**Comment by frankh** [comment]
I believe the error emails are built in to django, if you unset ADMIN_EMAIL you should stop receiving them
